"use client";
import {useEffect,useState} from "react";import {api} from "@/lib/api";
const AUD=[["all","Everyone"],["verified","Verified only"],["sellers","Sellers"],["buyers","Buyers"],["inactive","Inactive users"],["community","A community"],["users","Specific people"]];
export default function EmailCentre(){
 const [aud,setAud]=useState("all");const [cs,setCs]=useState<any[]>([]);const [comm,setComm]=useState("");const [picked,setPicked]=useState<any[]>([]);const [q,setQ]=useState("");const [res,setRes]=useState<any[]>([]);
 const [f,setF]=useState({subject:"",heading:"",body:"",ctaLabel:"",ctaUrl:"",scheduleAt:""});const [wide,setWide]=useState(true);const [hist,setHist]=useState<any[]>([]);const [msg,setMsg]=useState("");
 const loadH=()=>api("/admin/email/history").then(setHist).catch(()=>{});useEffect(()=>{api("/communities").then(setCs).catch(()=>{});loadH()},[]);
 useEffect(()=>{if(q.length<2)return setRes([]);const t=setTimeout(()=>api("/admin/users?q="+encodeURIComponent(q)).then(setRes).catch(()=>{}),250);return()=>clearTimeout(t)},[q]);
 const set=(k:string)=>(e:any)=>setF({...f,[k]:e.target.value});const audience=aud==="community"?{type:aud,communityId:comm}:aud==="users"?{type:aud,userIds:picked.map(p=>p._id)}:{type:aud};
 async function send(e:React.FormEvent){e.preventDefault();setMsg("");if(!confirm("Send this email?"))return;
  try{const b=await api("/admin/email/send",{method:"POST",body:JSON.stringify({audience,...f,scheduleAt:f.scheduleAt?new Date(f.scheduleAt).toISOString():undefined})});setMsg(`Queued for ${b.recipientCount} recipients.`);loadH();}catch(x:any){setMsg(x.message)}}
 async function test(){setMsg("");try{const me=await api("/users/me");await api("/admin/email/test",{method:"POST",body:JSON.stringify({to:me.email,subject:f.subject,heading:f.heading||f.subject,body:f.body})});setMsg("Test sent to "+me.email);}catch(x:any){setMsg(x.message)}}
 return(<div className="space-y-6"><h1 className="text-2xl">Email Centre</h1><div className="grid lg:grid-cols-2 gap-6">
  <form onSubmit={send} className="card p-5 space-y-3"><div><label className="label" htmlFor="a">Recipients</label><select id="a" className="input" value={aud} onChange={e=>setAud(e.target.value)}>{AUD.map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></div>
   {aud==="community"&&<select aria-label="Community" className="input" value={comm} onChange={e=>setComm(e.target.value)} required><option value="">Choose community</option>{cs.map(c=><option key={c._id} value={c._id}>{c.name}</option>)}</select>}
   {aud==="users"&&<div><input className="input" placeholder="Search by name or exact email" aria-label="Find user" value={q} onChange={e=>setQ(e.target.value)}/>
    <ul className="mt-2 space-y-1">{res.slice(0,5).map(u=><li key={u._id}><button type="button" className="text-sm text-primary min-h-[36px]" onClick={()=>{if(!picked.some(p=>p._id===u._id))setPicked([...picked,u]);setQ("")}}>Add {u.username}</button></li>)}</ul>
    <div className="flex flex-wrap gap-2 mt-2">{picked.map(p=><button type="button" key={p._id} className="chip bg-soft border border-line" onClick={()=>setPicked(picked.filter(x=>x._id!==p._id))}>{p.username} x</button>)}</div></div>}
   <input className="input" placeholder="Subject" aria-label="Subject" value={f.subject} onChange={set("subject")} required/><input className="input" placeholder="Heading" aria-label="Heading" value={f.heading} onChange={set("heading")}/>
   <textarea className="input min-h-[140px] py-3" placeholder="Body (basic HTML allowed)" aria-label="Body" value={f.body} onChange={set("body")} required/>
   <div className="grid grid-cols-2 gap-2"><input className="input" placeholder="Button label" aria-label="Button label" value={f.ctaLabel} onChange={set("ctaLabel")}/><input className="input" placeholder="Button URL" aria-label="Button URL" value={f.ctaUrl} onChange={set("ctaUrl")}/></div>
   <div><label className="label" htmlFor="s">Schedule (optional)</label><input id="s" type="datetime-local" className="input" value={f.scheduleAt} onChange={set("scheduleAt")}/></div>
   {msg&&<p role="status" className="text-sm text-muted">{msg}</p>}<div className="flex gap-2"><button className="btn-primary flex-1">{f.scheduleAt?"Schedule":"Send now"}</button><button type="button" className="btn-ghost" onClick={test}>Test send</button></div></form>
  <div><div className="flex gap-2 mb-2">{[[true,"Desktop"],[false,"Mobile"]].map(([w,l])=><button key={String(l)} aria-pressed={wide===w} onClick={()=>setWide(w as boolean)} className={`chip min-h-[36px] px-4 border ${wide===w?"bg-primary text-white border-primary":"border-line bg-white"}`}>{l as string}</button>)}</div>
   <div className="bg-soft rounded-card p-4 overflow-x-auto"><div className="bg-white rounded-2xl overflow-hidden mx-auto" style={{width:wide?600:375,maxWidth:"100%"}}><div className="h-1.5 bg-primary"/><div className="p-6"><p className="font-display font-bold text-primary mb-4">ClashHub</p>
    <h2 className="text-xl mb-2">{f.heading||f.subject||"Heading"}</h2><div className="text-sm mb-4 whitespace-pre-line">{f.body.replace(/<[^>]*>/g,"")||"Your message"}</div>{f.ctaLabel&&<span className="inline-block bg-primary text-white rounded-full px-6 py-3 text-sm">{f.ctaLabel}</span>}</div></div></div></div></div>
  <section><h2 className="text-lg mb-3">History</h2><div className="card overflow-x-auto"><table className="w-full text-sm"><thead className="text-left text-muted"><tr>{["Subject","Recipients","Sent","Failed","Date"].map(h=><th key={h} className="p-3 font-medium">{h}</th>)}</tr></thead>
   <tbody>{hist.map(h=><tr key={h._id} className="border-t border-line"><td className="p-3">{h.subject}</td><td className="p-3">{h.recipientCount}</td><td className="p-3">{h.sent}</td><td className="p-3">{h.failed}</td><td className="p-3">{new Date(h.createdAt).toLocaleString()}</td></tr>)}</tbody></table>{!hist.length&&<p className="p-6 text-center text-muted">No emails sent yet.</p>}</div></section></div>);
}
