export const PAGES:Record<string,{title:string;body:[string,string][]}>={
 about:{title:"About ClashHub",body:[["What we do","ClashHub is a mobile-first home for mobile gamers. Join a community for your game, run refereed matches and tournaments, and buy or sell game accounts through a trusted middleman."],["Why it exists","Account trading and match organising usually happen in scattered chats with no accountability. ClashHub puts referees, results and every deal on the record."]]},
 faq:{title:"FAQ",body:[["Is ClashHub free to join?","Yes. You need a verified email to chat, join, post or buy."],["Who can see who is selling an account?","Only the ClashHub admin. Buyers and sellers never chat directly."],["Can a referee change a result?","No. Referees submit once. Participants can appeal within the appeal window, and the admin makes the final call."],["How do I get paid as a seller?","The admin confirms the buyer's payment, then arranges payment to you. Follow the instructions in your admin chat."]]},
 "how-to-buy":{title:"How to buy",body:[["1. Find a listing","Browse the Games Store. Every listing is reviewed and marked Verified by ClashHub."],["2. Message the admin","Tap Buy / Message Admin. A private chat opens with the listing attached."],["3. Pay","Follow the payment instructions in the chat and upload your proof of payment."],["4. Receive your account","After payment is confirmed the admin delivers the account details in the chat and you get a receipt by email."]]},
 "how-to-sell":{title:"How to sell",body:[["1. Submit a listing","Use Sell a Game. Add clear images, an honest description and your account details. Details are stored encrypted and only the admin can see them."],["2. Get verified","The admin may message you to verify the account before approving."],["3. Stay hidden","Buyers never see who you are. The admin handles the buyer and asks you to hand over the account only after payment is confirmed."]]},
 "trust-and-safety":{title:"Trust and Safety",body:[["Every sale goes through the admin","Nobody trades directly. The admin verifies listings, collects payment, delivers the account and keeps the full record."],["Keep deals on ClashHub","Sharing phone numbers or external links in group chat is blocked. Anyone asking you to pay outside the platform should be reported."],["Report anything suspicious","Use the report buttons on messages, listings and users. Repeat offenders are suspended."]]},
 "marketplace-rules":{title:"Marketplace Rules",body:[["Listings","Only list accounts you own. No stolen, hacked or shared accounts. Descriptions and images must be accurate."],["Payments","Pay only to the account details the admin sends inside ClashHub chat."],["Disputes","Raise problems in your admin chat. The admin keeps chat and payment proof for every deal and makes the final decision."],["Enforcement","Violations can lead to removed listings, suspension or a ban."]]},
 terms:{title:"Terms of Service",body:[["Draft notice","This is a starter draft. Have it reviewed by a lawyer before launch."],["Using ClashHub","You must provide accurate information, keep your login secure and follow the Marketplace Rules. You are responsible for activity on your account."],["Marketplace","ClashHub acts as an intermediary for account sales. Listings can be rejected or removed at the admin's discretion."],["Suspension","We may suspend or ban accounts that break these terms."]]},
 privacy:{title:"Privacy Policy",body:[["Draft notice","This is a starter draft. Have it reviewed by a lawyer before launch."],["What we collect","Username, email, profile details, match and marketplace activity, and messages sent through the platform."],["How we use it","To run your account, verify deals, send transactional emails and keep the platform safe. Seller identity is visible only to the admin."],["Your choices","You can turn off optional emails and delete your account in Settings. Deal and match history may be kept in anonymised form for dispute handling."]]},
 cookies:{title:"Cookie Policy",body:[["Draft notice","This is a starter draft. Have it reviewed by a lawyer before launch."],["Essential (always on)","A secure, HTTP-only sign-in cookie keeps you logged in for up to 30 days. Your cookie choice and a few interface preferences are stored in your browser. These are needed for ClashHub to work."],["Security check","Our sign-up, log-in and contact forms use Cloudflare Turnstile to block bots. Cloudflare may set its own technical cookies for this."],["Analytics (optional, off by default)","If enabled by you, we load privacy-friendly analytics to understand how the site is used. Nothing loads until you opt in."],["Your choices","Use Cookie settings in the footer at any time to change or withdraw consent."]]},
 contact:{title:"Contact",body:[["Get in touch","Send us a message and the ClashHub team will reply by email."]]},
};
